### ISSUE TITLE
Visualization Tutorial DICOM Database

### ISSUE THREAD

**Issue by LuskasHusty** [SlicerLatinAmerica/TestSlicerTutorials#2]
The Visualization Tutorial fails when it gets to the step where it's supposed to load the DICOM database. 
I would also suggest that these temporary paths either be changed to a path within the TutorialMaker Module as a ignored file, or even better, handled by 3d slicer itself ( slicer.util.tempDirectory() ).

Console Output:
````
slicer.app.temporaryPath = C:/Users/{user}/AppData/Local/Temp/Slicer
slicer.app.defaultScenePath = C:/Users/{user}/Documents
slicer.dicomDatabase.databaseDirectory = C:/Users/{user}/Documents/SlicerDICOMDatabase
[Qt] Database folder does not contain ctkDICOM.sql file: C:/Users/{user}/Documents/SlicerDICOMDatabase
[Qt] Database folder does not contain ctkDICOM.sql file: C:/Users/{user}/Documents/SlicerDICOMDatabase
[Qt] Database folder does not contain ctkDICOM.sql file: C:/Users/{user}/Documents/SlicerDICOMDatabase
Traceback (most recent call last):
  File "E:/Slicer3d/NewModules/TutorialMaker/TutorialMaker/TutorialMaker.py", line 171, in annotateButton
    self.logic.Annotate(self.__selectedTutorial)
  File "E:/Slicer3d/NewModules/TutorialMaker/TutorialMaker/TutorialMaker.py", line 240, in Annotate
    TutorialMakerTest().test_TutorialMaker1(tutorialName)
  File "E:/Slicer3d/NewModules/TutorialMaker/TutorialMaker/TutorialMaker.py", line 351, in test_TutorialMaker1
    tutorial.runTest()
  File "E:\Slicer3d\NewModules\TutorialMaker\TutorialMaker\Testing\VisualizationTutorial.py", line 29, in runTest
    self.test_VisualizationTutorial1()
  File "E:\Slicer3d\NewModules\TutorialMaker\TutorialMaker\Testing\VisualizationTutorial.py", line 53, in test_VisualizationTutorial1
    self.runVisualizationTutorialPart1()
  File "E:\Slicer3d\NewModules\TutorialMaker\TutorialMaker\Testing\VisualizationTutorial.py", line 89, in runVisualizationTutorialPart1
    scroll_area[4].click()
  File "E:\Slicer3d\NewModules\TutorialMaker\TutorialMaker\Lib\utils.py", line 337, in click
    return self.__widgetData.click()
AttributeError: QHeaderView has no attribute named 'click'
````

**Comment by LuskasHusty** [comment]
There's also a new way to clip the models that is not compatible between the old Tutorials and Slicer 5.7.0

Old clipping options:
![image](https://github.com/user-attachments/assets/08c4b1ed-e14f-4fa4-b0a7-b255afb79723)

New clipping options:
![image](https://github.com/user-attachments/assets/1734aea3-0114-4df9-afe9-3e5abf9e3502)

**Comment by pauloguilhermepp** [comment]
I tried to load the DICOM data using the following function

![image](https://github.com/user-attachments/assets/6438bfd9-25fe-4e61-8a9a-2eebfe5ce520)


But got the following error:
![image](https://github.com/user-attachments/assets/c51a4629-cd38-4c00-b618-336876d82acc)

**Comment by LuskasHusty** [comment]
@pauloguilhermepp which slicer version are you using by the way?

**Comment by pauloguilhermepp** [comment]
I am currently using 3D Slicer 5.6.2.

**Comment by pauloguilhermepp** [comment]
Apparently, this error was happening when the standard Dicom path did not exist. I was able to solve it by creating the path in such cases. I will open a PR with this update.

**Comment by LuskasHusty** [comment]
The clipping is still not working on my end.

**Comment by pauloguilhermepp** [comment]
@LuskasHusty, I tested the updated code and it seems that it is working properly in the new 5.7 version of 3D Slicer:

![image](https://github.com/user-attachments/assets/1b19ce09-307a-46d0-a127-ddf976f85bf0)
